runtime: nodejs
env: flex

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "/home/ajrathore786/pucho1/PuchoTask3/My Project-97e210279755.json"
  AWS_ACCESS_KEY_ID: "AKIAJV7M56SABUQRVN5Q"
  AWS_SECRET_ACCESS_KEY: "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"